server:
  port: 8081

spring:
  application:
    name: ErpApp
  #profiles:
  #  active: dev #
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/erpapp?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: atdata
    password: atdata.1!!
    hikari:
      pool-name: HikariPool-${spring.application.name}
      #maximum-pool-size: 10        # 서비스 규모에 맞게 조절 (기본 10)
      #minimum-idle: 10             # maximum과 동일하게 맞추는 것이 성능상 유리 (Pool 충전 부하 방지)
      #connection-timeout: 30000    # 연결 시도 타임아웃 (30초)
      #idle-timeout: 600000         # 유휴 연결 유지 시간
      #max-lifetime: 1800000        # 연결 최대 수명 (DB의 wait_timeout보다 짧게 설정 필수)

logging:
  config: classpath:logback-spring.xml
  level:
    root: info
  file:
    path: ./log
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 3
      total-size-cap: 10MB
      #file-name-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%-5level]) ${PID:-} --- [%thread] %clr(%-40.40logger{36}){cyan} : %msg%n" # log font color
      file-name-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] ${PID:-} --- [%thread] %-40.40logger{36} : [%M:%L] %msg%n"

mybatis:
  mapper-locations: classpath*:mybatis/mariadb/**/*.xml
  #type-aliases-package: com.erpapp.domain.model
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'
    call-setters-on-nulls: true # 조회 데이터가 null일때 데이터의 key존재 유무
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 
    #default-statement-timeout: 60 # query excute time out, second
    lazy-loading-enabled: false # default false






