  
# database
spring:
  application:
    name: "springboot-study"
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mariadb://localhost:3306/springstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
    username: atdata
    password: atdata.1!!


# server port
server:
  port: 8081  


# log
logging:
  config: classpath:logback-config.xml
  level:
    root: info
    '[com.study]': debug
  file:
    path: ./log
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 3
      total-size-cap: 10MB
      file-name-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%-5level]) ${PID:-} --- [%thread] %clr(%-40.40logger{36}){cyan} : %msg%n"


# mybatis
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mariadb/**/*.xml




