server:
  port: 8081  
  servlet:
    session:
      timeout: 1m # default 30m
    context-path: / # http://localhost:8081/
    #context-path: /test # http://localhost:8081/test/
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      #force-request: true
      #force-response: true


spring:
  application:
    name: springboot-security
  servlet:
    multipart:
      max-file-size: 10MB # default 1MB
      max-request-size: 100MB # default 10MB
      #location: D:\\workspace-sts\\upload\\
      location: ../upload
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mariadb://localhost:3306/springstudy?serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowMultiQueries=true
    username: atdata
    password: atdata.1!!
    hikari:
      pool-name: HikariPool-${spring.application.name}
  thymeleaf:
    prefix: classpath:/templates/thymeleaf
    suffix: .html
    cache: false


logging:
  config: classpath:logback-config.xml
  level:
    root: info
  file:
    path: ./log
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
      max-file-size: 1MB
      max-history: 3
      total-size-cap: 10MB
      #file-name-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} %clr([%-5level]) ${PID:-} --- [%thread] %clr(%-40.40logger{36}){cyan} : %msg%n"
      file-name-pattern: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] ${PID:-} --- [%thread] %-40.40logger{36} : [%M:%L] %msg%n"


mybatis:
  #configuration:
  #  map-underscore-to-camel-case: true
  #  type-aliases-package: com.study.codingrecipe.board.dto.BoardDto
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mariadb/**/*.xml


project-set:
  location-image:
    product-thumbnail: /image/product/thumbnail
    product-detail: /image/product/detail

